# Site settings
title: "PORTFOLIO"
email: "arif.buet19@gmail.com"
description: >-
  Prospective PhD student and researcher.
  Focused on Computational Fluid Dynamics, Renewable Energy, Heat Transfer, Optimization, and Machine Learning.
twitter_username: username
github_username: username
minimal_mistakes_skin: "neon"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jemoji 
  - jekyll-include-cache

author:
  name: "Md. Ariful Islam"
  avatar: "/assets/images/arif.jpg"
  bio: "Prospective PhD Student."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/md-ariful-islam01/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Md-Ariful-Islam-55"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=tTVVlP8AAAAJ&hl=en"
    - label: "arif.buet19@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arif.buet19@gmail.com"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arif.buet19@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/md-ariful-islam01/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arifulportfolio"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Md-Ariful-Islam-55"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=tTVVlP8AAAAJ&hl=en"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
