# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "PORTFOLIO"
email: "arif.buet19@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Prospective PhD student and researcher.
  Focused on Computational Fluid Dynamics, Renewable Energy, Heat Transfer, Optimization, and Machine Learning.
twitter_username: username
github_username: username
minimal_mistakes_skin: "neon"
#search: true


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



# Plugins (previously gems:)
plugins:
- jekyll-paginate 
- jekyll-sitemap 
- jekyll-gist 
#- jekyll-feed 
- jemoji 
- jekyll-include-cache



author:
  name: "Md. Ariful Islam"
  avatar: "/assets/images/arif.jpg"
  bio: "Prospective PhD Student."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arif.buet19@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/md-ariful-islam01/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Md-Ariful-Islam-55"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"  # You can adjust the icon if preferred
      url: "https://scholar.google.com/citations?user=tTVVlP8AAAAJ&hl=en"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arif.buet19@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/md-ariful-islam01/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/arifulportfolio"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Md-Ariful-Islam-55"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"  # Same icon as for author
      url: "https://scholar.google.com/citations?user=tTVVlP8AAAAJ&hl=en"

   


defaults:



  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
